name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        scala: [3.3.0]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 20
          check-latest: true

      - name: Coursier cache
        uses: coursier/cache-action@v6

      - name: Check formatting
        run: sbt fixCheck

      - name: Compile and test
        run: sbt test
